### PR TITLE
Also apply volumes and custom configs from spec to init containers

### PR DESCRIPTION
**Pull request by sergicastro**
Part of: https://github.com/tetrateio/tetrate/issues/23240

This PR applies the custom config map and the custom volumes from the Kubegres spec to the init containers from the stateful sets, as it does for the main containers.
It also makes failover to use the custom config map in case it contains the script to promote replicas.

This allows TSB to configure volumes containing the TLS certificates and custom scripts that execute replica initialization using the TLS certs to connect to the primary instance.

### CODE REVIEW

**Comment by sergicastro** [comment]
Detected an issue executing failover. Working on the fix.

**Comment by sergicastro** [comment]
The last commit fixes the issue in the failover, and also extends the tests by:
- making the failover test to execute failover twice
- adding a test using custom configs and executing the failover twice

**Review by nacx — DISMISSED** [review]

**Comment by sergicastro** [comment]
I just found upgrade from older version with not custom-config is failing.
I want to fix it in the same PR, so holding until i push the fix with a test :)

**Comment by sergicastro** [comment]
The last commit fixes the problem with upgrading a volume from the base config to the custom config map. PTAL again @nacx

**Review by nacx — APPROVED** [review]

**Pull request merged**
